import{a as i,s as f,i as u}from"./assets/vendor-ef0f874b.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();i.defaults.headers.common["x-api-key"]="live_dqzx9gGAsy51dR76MW9oEWTcXRgRll8obeNyIbK5hMBfq7RtotA3JTBEj9B0oO9c";i.defaults.baseURL="https://api.thecatapi.com/v1";function m(){return i.get("breeds")}function h(t){return i.get(`images/search?breed_ids=${t}`)}const d={select:document.querySelector(".breed-select"),container:document.querySelector(".cat-info"),loader:document.querySelector(".loader"),error:document.querySelector(".error")},a=t=>d[t].classList.remove("visually-hidden"),c=t=>d[t].classList.add("visually-hidden"),p=t=>{a("loader"),c("select"),m().then(({data:s})=>{const r=s.map(({id:e,name:o})=>({text:o,value:e}));new f({select:".breed-select",placeholder:"Select a breed",searchPlaceholder:"Search a breed",data:r,events:{afterChange:e=>n(e[0].value)}}),a("select")}).catch(s=>{u.error({title:"Error",message:s.message,position:"center"})}).finally(()=>{c("loader")});const n=s=>{c("container"),a("loader"),h(s).then(r=>{if(!r.data)throw new Error("Empty response");if(!r.data[0].breeds)throw new Error("Empty breeds data");if(!r.data[0].breeds.length)throw new Error("Breed not found");const e=r.data[0].breeds[0];r.data[0].url&&(e.url=r.data[0].url),y(e)}).catch(r=>{u.error({title:"Error",message:r.message,position:"center"})}).finally(()=>{c("loader")})}},y=t=>{d.container.innerHTML=`
      <img src="${t.url}" alt="${t.name}" />
      <div>
        <h2 class="title">${t.name}</h2>
        <p class="description">${t.description}</p>
        <p><strong>Temperament:</strong> ${t.temperament}</p>
      </div>
    `,a("container")};p();
//# sourceMappingURL=commonHelpers.js.map
